# Generated by Django 6.0.3 on 2026-03-15 00:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "configuracion",
                    models.JSONField(
                        default=dict,
                        help_text="Estructura: {pasos: [{id, titulo, descripcion, campos: [{id, tipo, label, requerido, opciones, min, max}]}]}",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("moneda", models.CharField(default="COP", max_length=3)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotizadores",
                        to="accounts.negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "cotizador",
                "verbose_name_plural": "cotizadores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReglaPrecio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "formula",
                    models.CharField(
                        help_text="Ej: base * area + extra. Variables disponibles vienen del JSONField.",
                        max_length=500,
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict, help_text='Ej: {"base": 50000, "extra": 10000}'
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("prioridad", models.PositiveIntegerField(default=0)),
                (
                    "cotizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_precio",
                        to="cotizadores.cotizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "regla de precio",
                "verbose_name_plural": "reglas de precio",
                "ordering": ["prioridad", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="cotizador",
            constraint=models.UniqueConstraint(
                fields=("negocio", "slug"), name="unique_cotizador_slug_per_negocio"
            ),
        ),
    ]
