# Generated by Django 6.0.3 on 2026-03-15 00:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("cotizadores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("lista", "Lista"),
                            ("enviada", "Enviada"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("prospecto_nombre", models.CharField(max_length=255)),
                ("prospecto_email", models.EmailField(max_length=254)),
                ("prospecto_telefono", models.CharField(blank=True, max_length=20)),
                ("prospecto_empresa", models.CharField(blank=True, max_length=255)),
                ("respuestas", models.JSONField(default=dict)),
                ("desglose_precio", models.JSONField(default=list)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("moneda", models.CharField(default="COP", max_length=3)),
                ("descripcion_ia", models.TextField(blank=True)),
                ("pdf_url", models.URLField(blank=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "cotizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotizaciones",
                        to="cotizadores.cotizador",
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotizaciones",
                        to="accounts.negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "cotizacion",
                "verbose_name_plural": "cotizaciones",
                "ordering": ["-created_at"],
            },
        ),
    ]
