# Generated by Django 6.0.3 on 2026-03-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="fecha_aceptacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="ip_aceptacion",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="token_aceptacion",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
