# Generated by Django 6.0.3 on 2026-03-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="negocio",
            name="logo",
        ),
        migrations.AddField(
            model_name="negocio",
            name="logo_url",
            field=models.URLField(blank=True, default="", verbose_name="URL del logo"),
        ),
    ]
